spring.application.name=pedidos-service
server.port=8080

# Configuracion PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/Pedidos_Delivery
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA y Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# Carga de datos iniciales
spring.sql.init.mode=always

# Configuracion JWT
jwt.secret=9a3b6c8e1f4a7c0d2e5b8a1f4c7e0d3b6a9c2e5f8b1a4d7e0c3b6f9a2e5d8b1c
jwt.expiration=86400000